# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d316075d833454b9fba10b3b9bc460ef0c170d6f86ea489a876d3cf0f7eddf1ff99a23e40d61cd270edb84661e7ef6fb38fc50397aca7f8663287bd85e2a618

test:
  secret_key_base: adae1d10f377c95e4574bd2c9e1eac64a140cfa5c530ffea473c45d9facc5dc27b20f2f862d771ff739daa061b39b8bdf12dde9804170e91136ccf03e7d09600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
